version: "3"
services:
  www:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx/
      - ./:/usr/share/nginx/html

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/logs:/var/log/php
      - ./:/usr/share/nginx/html
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - 9000:9000